const usersDb = {
  "amir.zad@contractika.com": {
    id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
    username: "autoGeneratedForAPIUseOnly",
    email: "amir.zad@contractika.com",
    password: "myPassword",
    firstName: "Amir Mohsen",
    lastName: "Hossein Zadeh",
  },
};
const usersPrefrencesDb = {
  "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff": {
    theme: "dark",
    verified: false,
    currencySign: "$",
    currencyCode: "USD",
    locale: "en",
    profileImage: "",
  },
};

export const userByEmail = async (email) => usersDb[email];
export const prefByUserId = async (userId) => usersPrefrencesDb[userId];
