const axios = require("axios").default;

const usersDb = {
  "amir.zad@contractika.com": {
    id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
    username: "autoGeneratedForAPIUseOnly",
    email: "amir.zad@contractika.com",
    password: "myPassword",
    firstName: "Amir Mohsen",
    lastName: "Hossein Zadeh",
  },
};
const usersPrefrencesDb = {
  "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff": {
    theme: "dark",
    verified: false,
    currencySign: "$",
    currencyCode: "USD",
    locale: "en",
    profileImage: "",
  },
};

//export const userBy = async ({ email, password }) => usersDb[email];
export const userBy = async ({ email, password }) => {
  const { data } = await axios.post(`/backend/users`, {
    email,
    password,
  });
  return data;
};
export const prefBy = async (userId) => usersPrefrencesDb[userId];
