version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:14.10.1
        auth:
          username: hypbox
          password: $DOCKER_HUB_PASSWORD
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: npm i
      - run:
          name: Building
          command: npm run build
      - run:
          name: Running Tests
          command: npm t
