const AUTH_URL = "/auth";

export default (mock) => [
  mock.onPost(`${AUTH_URL}/login`).reply(200, {
    access_token: "mock",
    refresh_token: "mock-7d9d-48e9-9ce8-cd86b47b9b85",
  }),
];

// "amir.zad@contractika.com": {
//   id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
//   username: "autoGeneratedForAPIUseOnly",
//   email: "amir.zad@contractika.com",
//   password: "myPassword",
//   firstName: "Amir Mohsen",
//   lastName: "Hossein Zadeh",
// },
// };
// const usersPrefrencesDb = {
// "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff": {
//   theme: "dark",
//   verified: false,
//   currencySign: "$",
//   currencyCode: "USD",
//   locale: "en",
//   profileImage: "",
// },
