const API_URL = "/backend";

const users = [
  {
    id: "USER1ID",
    username: "USERNAME2", //autoGeneratedForAPIUseOnly
    email: "NAME.LAST@DOMAIN.com",
    password: "PASSWORD",
    firstName: "FIRSTNAME",
    lastName: "LASTNAME",
  },
];

const userSettings = [
  {
    id: "USER1ID",
    theme: "dark",
    verified: false,
    currencySign: "$",
    currencyCode: "USD",
    locale: "en",
    profileImage: "",
  },
];

const user1 = users[0];
const user1Settings = userSettings[0];

export default (mock) => [
  mock.onGet(`${API_URL}/users`).reply(200, users),
  mock
    .onPost(`${API_URL}/users`, {
      email: user1.email,
      password: user1.password,
    })
    .reply(200, users[0]),
  mock.onGet(`${API_URL}/users/${user1.id}/settings`).reply(200, user1Settings),
];
