const API_URL = "/backend";

const users = [
  {
    id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
    username: "USERNAME2", //autoGeneratedForAPIUseOnly
    email: "NAME.LAST@DOMAIN.com",
    password: "PASSWORD",
    firstName: "FIRSTNAME",
    lastName: "LASTNAME",
  },
];

const { email, password } = users[0];

export default (mock) => [
  mock.onGet(`${API_URL}/users`).reply(200, users),
  mock.onPost(`${API_URL}/users`, { email, password }).reply(200, users[0]),
];

// "amir.zad@contractika.com": {
//   id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
//   username: "autoGeneratedForAPIUseOnly",
//   email: "amir.zad@contractika.com",
//   password: "myPassword",
//   firstName: "Amir Mohsen",
//   lastName: "Hossein Zadeh",
// },
// };
// const usersPrefrencesDb = {
// "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff": {
//   theme: "dark",
//   verified: false,
//   currencySign: "$",
//   currencyCode: "USD",
//   locale: "en",
//   profileImage: "",
// },
