const API_URL = "/backend";

export default (mock) => [
  mock.onGet(`${API_URL}/users`).reply(200, [
    {
      id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
      username: "USERNAME2", //autoGeneratedForAPIUseOnly
      email: "NAME.LAST@DOMAIN.com",
      password: "PASSWORD",
      firstName: "FIRSTNAME",
      lastName: "LASTNAME",
    },
  ]),
];

// "amir.zad@contractika.com": {
//   id: "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff",
//   username: "autoGeneratedForAPIUseOnly",
//   email: "amir.zad@contractika.com",
//   password: "myPassword",
//   firstName: "Amir Mohsen",
//   lastName: "Hossein Zadeh",
// },
// };
// const usersPrefrencesDb = {
// "4bfcfa19-6d00-4a23-8549-d5cf55f4a0ff": {
//   theme: "dark",
//   verified: false,
//   currencySign: "$",
//   currencyCode: "USD",
//   locale: "en",
//   profileImage: "",
// },
